# Generated by Django 5.2.7 on 2025-11-15 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('repo_cont', models.TextField(max_length=2000, verbose_name='報告内容')),
                ('repo_plac', models.CharField(choices=[('受付', '受付'), ('直前待機場所', '直前待機場所'), ('ステージ・客席（設備）', 'ステージ・客席（設備）'), ('ステージ・客席（演奏）', 'ステージ・客席（演奏）'), ('スタッフエリア', 'スタッフエリア'), ('会場周辺', '会場周辺'), ('全域', '全域'), ('その他', 'その他')], max_length=15, verbose_name='発生場所')),
                ('repo_pter', models.CharField(max_length=15, verbose_name='報告者')),
            ],
            options={
                'permissions': [('make_report', '報告権限'), ('view_reports', '報告閲覧権限')],
            },
        ),
    ]
