# Generated by Django 5.2.7 on 2025-11-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='repo_publicity',
            field=models.CharField(choices=[('受付', '受付'), ('直前待機場所', '直前待機場所'), ('ステージ・客席（設備）', 'ステージ・客席（設備）'), ('ステージ・客席（演奏）', 'ステージ・客席（演奏）'), ('スタッフエリア', 'スタッフエリア'), ('会場周辺', '会場周辺'), ('全域', '全域'), ('その他', 'その他')], default='private', max_length=15, verbose_name='表示設定'),
            preserve_default=False,
        ),
    ]
