# Generated by Django 5.2.7 on 2025-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_repo_publicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_publicity',
            field=models.CharField(choices=[('public', '全体に表示'), ('only_staff', 'スタッフのみに表示'), ('private', '非表示')], max_length=15, verbose_name='表示設定'),
        ),
    ]
