# Generated by Django 5.2.7 on 2025-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_repo_publicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_plac',
            field=models.CharField(blank=True, choices=[('受付', '受付'), ('直前待機場所', '直前待機場所'), ('ステージ・客席（設備）', 'ステージ・客席（設備）'), ('ステージ・客席（演奏）', 'ステージ・客席（演奏）'), ('スタッフエリア', 'スタッフエリア'), ('会場周辺', '会場周辺'), ('全域', '全域'), ('その他', 'その他')], max_length=15, null=True, verbose_name='発生場所'),
        ),
        migrations.AlterField(
            model_name='report',
            name='repo_publicity',
            field=models.CharField(choices=[('public', '全体に表示'), ('only_staff', 'スタッフのみに表示'), ('private', '非表示')], default='only_staff', max_length=15, verbose_name='表示設定'),
        ),
    ]
