# Generated by Django 5.2.7 on 2025-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_repo_plac_alter_report_repo_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='repo_tweet',
            field=models.BooleanField(default=False, verbose_name='つぶやきモード'),
        ),
    ]
