# Generated by Django 5.2.7 on 2025-10-29 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('repo_cont', models.TextField(max_length=2000, verbose_name='報告内容')),
                ('repo_plac', models.CharField(choices=[('受付', '受付'), ('直前待機場所', '直前待機場所'), ('ステージ・客席（設備）', 'ステージ・客席（設備）'), ('ステージ・客席（演奏）', 'ステージ・客席（演奏）'), ('スタッフエリア', 'スタッフエリア'), ('会場周辺', '会場周辺'), ('全域', '全域'), ('その他', 'その他')], max_length=15, verbose_name='発生場所')),
                ('repo_pter', models.CharField(max_length=15, verbose_name='報告者')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='団体名')),
                ('team_desc', models.CharField(max_length=100, verbose_name='団体の説明')),
                ('onstage_time', models.DateTimeField(verbose_name='出演予定時刻')),
                ('checkin_pretime_1', models.DateTimeField(verbose_name='受付日時の予定')),
                ('checkin_postime_1', models.DateTimeField(blank=True, null=True, verbose_name='実際の受付日時')),
                ('checkin_charge_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名')),
                ('file_stage', models.FileField(blank=True, null=True, upload_to='website_app/files/', verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
