# Generated by Django 5.2.7 on 2025-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='checkin_charge_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='team',
            name='checkin_postime_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='実際の直前待機日時'),
        ),
        migrations.AddField(
            model_name='team',
            name='checkin_pretime_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='直前待機日時の予定'),
        ),
        migrations.AddField(
            model_name='team',
            name='file_form',
            field=models.FileField(blank=True, null=True, upload_to='website_app/form_files/', verbose_name='応募ファイル'),
        ),
        migrations.AddField(
            model_name='team',
            name='onstage_time_acc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='実際の出演時刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='file_stage',
            field=models.FileField(blank=True, null=True, upload_to='website_app/stage_files/', verbose_name='ステージファイル'),
        ),
    ]
