# Generated by Django 5.2.7 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_team_checkin_charge_2_team_checkin_postime_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rehearsal_duration',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='出演分数'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_charge_1',
            field=models.CharField(blank=True, null=True, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_charge_2',
            field=models.CharField(blank=True, null=True, verbose_name='担当者'),
        ),
    ]
