# Generated by Django 5.2.7 on 2025-11-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_team_rehearsal_duration_alter_team_checkin_charge_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='rehearsal_duration',
            new_name='duration_onst',
        ),
        migrations.AddField(
            model_name='team',
            name='duration_reha',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='リハ分数'),
        ),
    ]
