# Generated by Django 5.2.7 on 2025-11-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_rename_rehearsal_duration_team_duration_onst_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_reception_list', '受付リストを閲覧できる'), ('update_reception', '受付到着印を押せる')]},
        ),
    ]
