# Generated by Django 5.2.7 on 2025-11-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('initial_registration', '団体の初期登録を出来る'), ('checkin', '舞台進行を操作できる'), ('view_detail', '舞台進行を操作できる'), ('update_information', '舞台進行を操作できる'), ('make_report', '舞台進行を操作できる'), ('view_reports', '舞台進行を操作できる')]},
        ),
    ]
