# Generated by Django 5.2.7 on 2025-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('make_report', '報告権限'), ('view_reports', '報告閲覧権限')]},
        ),
    ]
