# Generated by Django 5.2.7 on 2025-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
