# Generated by Django 5.2.7 on 2025-11-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('initial_registration', '団体初期登録権限'), ('checkin', '打刻権限'), ('view_detail', '団体詳細確認権限'), ('update_information', '団体情報更新権限')]},
        ),
    ]
