# Generated by Django 5.2.7 on 2025-11-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0011_alter_team_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='checkin_charge_1',
        ),
        migrations.AddField(
            model_name='team',
            name='checkin_charge_3',
            field=models.CharField(blank=True, null=True, verbose_name='代表者電話番号'),
        ),
        migrations.AddField(
            model_name='team',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_equip',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='使用機材等'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name_kana',
            field=models.CharField(default='ナシ', verbose_name='団体名（カナ）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_ninzu',
            field=models.IntegerField(blank=True, null=True, verbose_name='参加人数'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_rep',
            field=models.CharField(blank=True, null=True, verbose_name='代表者名（カナ）'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_charge_2',
            field=models.CharField(blank=True, null=True, verbose_name='代表者メールアドレス'),
        ),
    ]
