# Generated by Django 5.2.7 on 2025-11-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_remove_team_checkin_charge_1_team_checkin_charge_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='checkin_charge_2',
            new_name='team_rep_mail',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='checkin_charge_3',
            new_name='team_rep_tel',
        ),
    ]
