# Generated by Django 5.2.7 on 2025-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_rename_checkin_charge_2_team_team_rep_mail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='団体の所属'),
        ),
    ]
