# Generated by Django 5.2.7 on 2025-11-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0014_delete_report_alter_team_team_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='file_artpic',
            field=models.ImageField(blank=True, null=True, upload_to='website_app/art_pictures/', verbose_name='アーティスト写真'),
        ),
    ]
