# Generated by Django 5.2.7 on 2025-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0015_team_file_artpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='checkin_koedashi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='声出し可能時間'),
        ),
        migrations.AddField(
            model_name='team',
            name='duration_koed',
            field=models.IntegerField(blank=True, default=17, null=True, verbose_name='声出し分数'),
        ),
    ]
