# Generated by Django 5.2.7 on 2025-11-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0016_team_checkin_koedashi_team_duration_koed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_belong',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='団体の所属'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='団体説明'),
        ),
    ]
