# Generated by Django 5.2.7 on 2025-11-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0017_team_team_belong_alter_team_team_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='onstage_tien_acc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終演打刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_koedashi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='声出し開始定刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_postime_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='受付打刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_postime_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='控室到着打刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_pretime_1',
            field=models.DateTimeField(verbose_name='受付定刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='checkin_pretime_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='控室到着定刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='onstage_time',
            field=models.DateTimeField(verbose_name='出演定刻'),
        ),
        migrations.AlterField(
            model_name='team',
            name='onstage_time_acc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開演打刻'),
        ),
    ]
