# Generated by Django 5.2.7 on 2025-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0018_team_onstage_tien_acc_alter_team_checkin_koedashi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='duration_onst',
            field=models.IntegerField(default=10, verbose_name='出演分数'),
        ),
        migrations.AlterField(
            model_name='team',
            name='duration_reha',
            field=models.IntegerField(default=5, verbose_name='リハ分数'),
        ),
    ]
