# Generated by Django 5.2.7 on 2025-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0019_alter_team_duration_onst_alter_team_duration_reha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='note',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='団体説明'),
        ),
    ]
