# Generated by Django 5.2.7 on 2025-10-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
